name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          fabricioveronez/kube-news:${{ github.run_number }}
          fabricioveronez/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.0
    - name: Configuração da credencial da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: us-east-1
    - name: Configurar o KubeConfig
      run: echo "Configurar o KubeCOnfig"
    - name: Aplicar o deploy
      run: echo "Executar o Kubectl apply"
